name: Deploy to AWS
on:
  push:
    branches:
      - main  # Or 'master', check your branch name!

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USERNAME }}
          key: ${{ secrets.AWS_KEY }}
          script: |
            # 1. Stop old containers
            sudo docker stop app_cloud || true
            sudo docker rm app_cloud || true
            
            # 2. Go to folder and pull latest code
            # (Assumes you cloned it to ~/stylish-devops)
            cd ~/stylish-devops
            git pull origin main
            
            # 3. Build new image
            sudo docker build -t stylish-devops:latest .
            
            # 4. Run new container (Connected to Atlas)
            sudo docker run -d -p 80:3000 \
              --name app_cloud \
              -e PORT=3000 \
              -e MONGODB_URI="mongodb+srv://admin:Khan4499@cluster0.e8q2lqv.mongodb.net/stylish-devops?retryWrites=true&w=majority" \
              -e JWT_SECRET=secret123 \
              stylish-devops:latest
